### ISSUE TITLE
Frame stuttering due to event spam (QUEST_DATA_LOAD_RESULT)

### ISSUE THREAD

**Issue by tflo** [Breeni/BtWTodo#1]
Installed your add-on only 2 hours ago, and noticed something weird:

While questing in Revendreth it behaved normally, but as I started doing the Korthia dailies I got a frequent and pretty hefty frame stuttering. 

I opened the event tracer and saw that every time I hit a modifier key (can be shift, ctrl, option or command/meta (I’m on a Mac)) a series of QUEST_DATA_LOAD_RESULT gets spammed, presumably for every Korthia-daily ID, which is quite a lot of stuff.

The stuttering this produces forces me to disable the add-on, at least in Korthia.

Notes:

- Happens also with all other add-ons unloaded
- The event spam seems to start only after a BtWTodo window has been opened (e.g. the tooltip window). So, maybe a reload and then avoiding to open any BtWTodo window would be a viable workaround for the moment. (Needs further testing.)

***
PS: v0.0.6-beta on WoW Retail

**Comment by tflo** [comment]
Update:

Quoting myself…

> So, maybe a reload and then avoiding to open any BtWTodo window would be a viable workaround for the moment. (Needs further testing.)

Also without opening a BtWTodo window, the event spam seems to get triggered by some other event later. So, not a workaround.

**Comment by Breeni** [comment]
Thank you for the report. I've pushed a new version (v0.0.7-beta) that should fix this issue, please let me know if it persists.

**Comment by tflo** [comment]
Only tested very briefly, but seems fine so far.

Many thanks for the swift fix!
