### ISSUE TITLE
Error thrown when trying to add state "Quest"

### ISSUE THREAD

**Issue by Fraktyl** [Breeni/BtWTodo#11]
Trying to add a Todo for the "Crossing Fate" quest.  

When I click anything in the drop down for the "Add State" area the following LUA error is generated.
`10x BtWTodo\Config.lua:878: attempt to index field 'AddItem' (a nil value)
[string "@BtWTodo\Config.lua"]:878: in function `Add'
[string "@BtWTodo\Config.lua"]:1612: in function `onchange'
[string "@BtWTodo\Config.lua"]:784: in function `SetSelected'
[string "@BtWTodo\Config.lua"]:746: in function `func'
[string "@SharedXML\UIDropDownMenu.lua"]:918: in function `UIDropDownMenuButton_OnClick'
[string "*:OnClick"]:1: in function <[string "*:OnClick"]:1>

Locals:
self = <unnamed> {
 0 = <userdata>
 OnLeave = <function> defined @BtWTodo\Config.lua:960
 pool = <table> {
 }
 SetScript = <function> defined @BtWTodo\Defines.lua:52
 RegisterSupportedScriptHandlers = <function> defined @BtWTodo\Defines.lua:36
 Update = <function> defined @BtWTodo\Config.lua:857
 OnMouseUp = <function> defined @BtWTodo\Config.lua:987
 Remove = <function> defined @BtWTodo\Config.lua:945
 OnDragStart = <function> defined @BtWTodo\Config.lua:962
 OnDrag = <function> defined @BtWTodo\Config.lua:974
 OnMouseWheel = <function> defined @BtWTodo\Config.lua:991
 RunScript = <function> defined @BtWTodo\Defines.lua:41
 OnDragStop = <function> defined @BtWTodo\Config.lua:971
 OnAddClick = <function> defined @BtWTodo\Config.lua:942
 scriptHandlers = <table> {
 }
 states = <table> {
 }
 supportedHandlers = <table> {
 }
 GetCount = <function> defined @BtWTodo\Config.lua:939
 OnMouseDown = <function> defined @BtWTodo\Config.lua:989
 Init = <function> defined @BtWTodo\Config.lua:847
 OnEnter = <function> defined @BtWTodo\Config.lua:958
 OnLoad = <function> defined @BtWTodo\Config.lua:840
 Add = <function> defined @BtWTodo\Config.lua:874
}
key = "quest"
frame = <unnamed> {
 0 = <userdata>
 Editor = <unnamed> {
 }
 ErrorText = <unnamed> {
 }
 RevertButton = <unnamed> {
 }
 AddStateText = <unnamed> {
 }
 ModeTabHeader = BtWTodoConfigTodoPanelModeTabHeader {
 }
 Name = <unnamed> {
 }
 AddButton = <unnamed> {
 }
 FunctionTabHeader = BtWTodoConfigTodoPanelFunctionTabHeader {
 }
 AddDropDown = <unnamed> {
 }
 Inset = <unnamed> {
 }
 States = <unnamed> {
 }
}
provider = <table> {
 GetID = <function> defined @BtWTodo\States/Quest.lua:204
 FillAutoComplete = <function> defined @BtWTodo\States/Quest.lua:250
 Init = <function> defined @BtWTodo\State.lua:54
 GetName = <function> defined @BtWTodo\States/Quest.lua:207
 RequiresID = <function> defined @BtWTodo\State.lua:65
 GetAddTitle = <function> defined @BtWTodo\States/Quest.lua:210
 ParseInput = <function> defined @BtWTodo\States/Quest.lua:240
 Acquire = <function> defined @BtWTodo\States/Quest.lua:213
 GetDefaults = <function> defined @BtWTodo\States/Quest.lua:235
 GetFunctions = <function> defined @BtWTodo\States/Quest.lua:216
 Supported = <function> defined @BtWTodo\State.lua:75
}
(*temporary) = nil
(*temporary) = nil
(*temporary) = true
(*temporary) = "Usage: GetStateProvider(provider): expected provider to be string"
(*temporary) = "string"
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to index field 'AddItem' (a nil value)"
Internal = <table> {
 ScriptHandlerMixin = <table> {
 }
 UpdateList = <function> defined @BtWTodo\Lists.lua:119
 GetList = <function> defined @BtWTodo\Lists.lua:102
 Get92SeasonWeek = <function> defined @BtWTodo\Register_Mainline.lua:47
 CompareTodos = <function> defined @BtWTodo\Core.lua:307
 GetStateProvider = <function> defined @BtWTodo\State.lua:110
 IterateStateProviders = <function> defined @BtWTodo\State.lua:128
 RegisterCustomStateFunction = <function> defined @BtWTodo\State.lua:134
 IterateTodos = <function> defined @BtWTodo\Core.lua:281
 ActionName = <function> defined @BtWTodo\Config.lua:595
 GenerateFunctionFromTable = <function> defined @BtWTodo\State.lua:305
 GetRegisteredTodo = <function> defined @BtWTodo\Core.lua:144
 SplitAction = <function> defined @BtWTodo\Config.lua:590
 GetTodoChangeLog = <function>`

**Comment by Breeni** [comment]
Thank you for letting me know. I've pushed a new version that should fix this issue (v0.0.40-beta). It may take a while to be available on the various addon sites. Please let me know if it persists.
