### ISSUE TITLE
Errors

### ISSUE THREAD

**Issue by Fizgig1973** [Breeni/BtWTodo#15]
Getting the following error when first entering the game.

410x BtWTodo/States/Currency.lua:45: attempt to index a nil value
[string "=(tail call)"]: ?
[string "@BtWTodo/State.lua"]:413: in function <BtWTodo/State.lua:412>
[string "=[C]"]: in function `xpcall'
[string "@BtWTodo/State.lua"]:412: in function `GetText'
[string "@BtWTodo/Windows.lua"]:42: in function `Update'
[string "@BtWTodo/Windows.lua"]:29: in function `Init'
[string "@BtWTodo/Windows.lua"]:194: in function `Update'
[string "@BtWTodo/Windows.lua"]:142: in function `Init'
[string "@BtWTodo/Windows.lua"]:242: in function `initializer'
[string "@Blizzard_SharedXML/Shared/Scroll/ScrollBoxListView.lua"]:372: in function `InvokeInitializer'
[string "@Blizzard_SharedXML/Shared/Scroll/ScrollBoxListView.lua"]:390: in function <...izzard_SharedXML/Shared/Scroll/ScrollBoxListView.lua:389>
[string "=[C]"]: in function `secureexecuterange'
...
[string "@Blizzard_Settings_Shared/Blizzard_SettingsPanel.lua"]:481: in function <.../Blizzard_Settings_Shared/Blizzard_SettingsPanel.lua:474>
[string "=[C]"]: in function `secureexecuterange'
[string "@Blizzard_Settings_Shared/Blizzard_SettingsPanel.lua"]:485: in function `ForEachCanvas'
[string "@Blizzard_Settings_Shared/Blizzard_SettingsPanel.lua"]:499: in function `CommitCanvases'
[string "@Blizzard_Settings_Shared/Blizzard_SettingsPanel.lua"]:203: in function `Commit'
[string "@Blizzard_Settings_Shared/Blizzard_SettingsPanel.lua"]:239: in function `ExitWithCommit'
[string "@Blizzard_Settings_Shared/Blizzard_SettingsPanel.lua"]:213: in function `Close'
[string "@Blizzard_UIParent/Mainline/UIParent.lua"]:2825: in function <...rfaceBlizzard_UIParent/Mainline/UIParent.lua:2792>
[string "=[C]"]: in function `ToggleGameMenu'
[string "TOGGLEGAMEMENU"]:1: in function <[string "TOGGLEGAMEMENU"]:1>

Locals:
(*temporary) = "down"

**Comment by Breeni** [comment]
I've uploaded a new version (v0.0.57-beta) that should fix this error although it seems like its trying to access a currency that doesn't exist. Please let me know if you have any other issues.
