### ISSUE TITLE
LUA Error on non-max level character

### ISSUE THREAD

**Issue by Fraktyl** [Breeni/BtWTodo#2]
Logging in on my level 51 hunter throws the following errors:

`13x [string "[Maw Assault:Text]"]:6: attempt to call global 'select' (a nil value)
[string "@BtWTodo\State.lua"]:383: in function <BtWTodo\State.lua:382>
[string "=[C]"]: in function `xpcall'
[string "@BtWTodo\State.lua"]:382: in function `GetText'
[string "@BtWTodo\Windows.lua"]:35: in function `Update'
[string "@BtWTodo\Windows.lua"]:22: in function `Init'
[string "@BtWTodo\Windows.lua"]:187: in function `Update'
[string "@BtWTodo\Windows.lua"]:135: in function `Init'
[string "@BtWTodo\Windows.lua"]:234: in function <BtWTodo\Windows.lua:233>
[string "@SharedXML\Scroll\ScrollBoxView.lua"]:391: in function `frameFactory'
[string "@SharedXML\Scroll\ScrollBoxView.lua"]:340: in function `Acquire'
[string "@SharedXML\Scroll\ScrollBoxView.lua"]:604: in function `Rebuild'
[string "@SharedXML\Scroll\ScrollBoxView.lua"]:667: in function `ValidateDataRange'
...
[string "@BtWTodo\Windows.lua"]:456: in function `func'
[string "@BtWTodo\Events.lua"]:73: in function `OnEvent'
[string "@BtWTodo\Events.lua"]:83: in function `TriggerEvent'
[string "@BtWTodo\Config.lua"]:1869: in function <BtWTodo\Config.lua:1849>
[string "=[C]"]: in function `xpcall'
[string "@BtWTodo\Config.lua"]:1849: in function <BtWTodo\Config.lua:1848>
[string "=[C]"]: in function `pcall'
[string "@FrameXML\InterfaceOptionsFrame.lua"]:207: in function <FrameXML\InterfaceOptionsFrame.lua:206>
[string "=[C]"]: ?
[string "@FrameXML\InterfaceOptionsFrame.lua"]:230: in function <FrameXML\InterfaceOptionsFrame.lua:222>`

I have removed 'Current Character' from the displayed character and also removed that character specifically from all lists.

**Comment by Breeni** [comment]
I've uploaded a new version (v0.0.13-beta) that should fix this issue, please let me know if it persists.

**Comment by Fraktyl** [comment]
Seems to work!  Thanks for the quick response!
