### ISSUE TITLE
Lua Error - GetPlayer called to early.

### ISSUE THREAD

**Issue by fireymerlin** [Breeni/BtWTodo#4]
I'm getting the following error when I first enter the game.
1x BtWTodo\Characters.lua:185: GetPlayer called to early, UnitFullName missing name or realm
[string "=[C]"]: in function `assert'
[string "@BtWTodo\Characters.lua"]:185: in function `GetPlayer'
[string "@BtWTodo\States/Keystone.lua"]:87: in function `func'
[string "@BtWTodo\Events.lua"]:73: in function <BtWTodo\Events.lua:57>

**Comment by Breeni** [comment]
This should be fixed with version v0.0.17-beta, please let me know if it persists.
