### ISSUE TITLE
Lua Error when accepting Korthia Dailies

### ISSUE THREAD

**Issue by Fraktyl** [Breeni/BtWTodo#5]
Version: v0.0.17-beta

Max level toon with renown 75.  Campaign is 3/9 steps complete.  Entering Korthia and accepting any quest throws this error:

`56x BtWTodo\Register_Mainline.lua:173: bad argument #1 to 'pairs' (table expected, got nil)
[string "@BtWTodo\Register_Mainline.lua"]:173: in function `GetKorthiaDailies'
[string "[Korthia:Text]"]:2: in function `text'
[string "@BtWTodo\State.lua"]:397: in function <BtWTodo\State.lua:396>
[string "=[C]"]: in function `xpcall'
[string "@BtWTodo\State.lua"]:396: in function `GetText'
[string "@BtWTodo\Windows.lua"]:35: in function `func'
[string "@BtWTodo\Events.lua"]:76: in function <BtWTodo\Events.lua:57>`

**Comment by Breeni** [comment]
Thanks for letting me know, it should be fixed as of version v0.0.18-beta, please let me know if it persists.
