### ISSUE TITLE
Error when opening

### ISSUE THREAD

**Issue by Weetbix813** [Breeni/BtWTodo#8]
Started getting this error today: 
4x BtWTodo\Config.lua:698: attempt to index local 'icon' (a nil value)
[string "=[C]"]: in function `xpcall'
[string "@BtWTodo\Config.lua"]:693: in function <BtWTodo\Config.lua:692>
[string "=[C]"]: in function `pcall'
[string "@FrameXML\InterfaceOptionsFrame.lua"]:207: in function <FrameXML\InterfaceOptionsFrame.lua:206>
[string "=[C]"]: ?
[string "@FrameXML\InterfaceOptionsFrame.lua"]:230: in function <FrameXML\InterfaceOptionsFrame.lua:222>

I just recently switched from using this via the minimap button to using the Titan panel plugin. The error occurs whenever I click on BtWTodo on my Titan panel or the minimap button (I re-enabled to test if I got the error then)

**Comment by Breeni** [comment]
Thanks for letting me know, it should be fixed in the latest version (v0.0.31-beta), please let me know if it persists.

**Comment by Weetbix813** [comment]
fixed :) thanks for a quick fix!
